export const QUIZ_ACTION_TYPES = {
  FETCH_QUESTIONS_START: "quiz/FETCH_QUESTIONS_START",
  FETCH_QUESTIONS_SUCCESS: "quiz/FETCH_QUESTIONS_SUCCESS",
  FETCH_QUESTIONS_FAILED: "quiz/FETCH_QUESTIONS_FAILED",
  UPDATE_CURRENT_QUESTION_INDEX: "quiz/UPDATE_CURRENT_QUESTION_INDEX",
  SELECT_ANSWER: "quiz/SELECT_ANSWER",
  RESET_QUESTIONS: "quiz/RESET_QUESTIONS",
};
